name: Deploy to Railway
'on':
  - push
  - pull_request
jobs:
  package:
    name: Maven Package (no tests)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Jar Builds
        uses: actions/upload-artifact@v4.4.2
        with:
          name: Jar with Builds
          path: target/*.jar
trivy-scan:
  name: Trivy Scan
  needs: package
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - name: Download Trivy
      run: >
        curl -LO
        https://github.com/aquasecurity/trivy/releases/latest/download/trivy_Linux_x86_64.tar.gz

        tar zxvf trivy_Linux_x86_64.tar.gz -C /usr/local/bin

        rm -f trivy_Linux_x86_64.tar.gz
    - name: Verify Trivy Installation
      run: trivy --version
    - name: Trivy Vulnerability Scan
      run: 'trivy fs . --exit-code 1 --severity HIGH,CRITICAL'
  documentation:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - uses: actions/checkout@v4
      - name: Dokka with Maven
        run: 'mvn -B dokka:dokka'
      - name: Archive KDoc Documentation
        uses: actions/upload-artifact@v4.4.2
        with:
          name: KDoc Documentation Site
          path: target/dokka
  test:
    name: Maven Tests
    needs: package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: Maven Verify
        run: mvn -B clean verify
  deploy:
    name: Railway Deploy
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Railway
        run: npm i -g @railway/cli
      - name: Deploy to Railway
        run: 'railway up --service ${{ secrets.RAILWAY_SERVICE }}'
        env:
          RAILWAY_TOKEN: '${{ secrets.RAILWAY_TOKEN }}'
